#pragma once

enum Status {
    SUCCESS,
    ALREADY_EXIST,
    NOT_FOUND,
    NOT_ENOUGH_BALANCE,
    FAILURE,
    MONEY_NOT_FOUND,
    ACCOUNT_NOT_FOUND,
    BANK_NOT_FOUND,
    RECIEVER_NOT_FOUND,
    PAYER_NOT_FOUND,
    NO_JOB,
    CLIENT_NOT_FOUND,
    BALANCE_IN_MAX,
    IN_COOLDOWN
};
